---
openapi: 3.0.3
info:
  title: MAD Project Backend
  description: MAD Backend API
  version: 1.0.0
servers:
- url: /
tags:
- name: Account
  description: To be fill in
- name: Attendance
  description: To be fill in
- name: Calendar
  description: To be fill in
- name: Home
  description: To be fill in
- name: Launch
  description: To be fill in
- name: Leave
  description: To be fill in
- name: NFC
  description: To be fill in
- name: Virtual Business Card
  description: To be fill in
paths:
  /account/create:
    post:
      tags:
      - Account
      description: |
        Example
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - onboardFormDataJSON
      responses:
        "200":
          description: Successfully created project onboarding ticket in the Jira board.
          content:
            application/json:
              schema:
                type: string
                example: Project onboarding ticket created successfully...
        "400":
          description: Failed to create project onboarding ticket in the Jira board.
          content:
            application/json:
              schema:
                type: string
                example: Failed to create ticket...
components: {}
