service: ${self:custom.CloudNamingIdentifier}-backend

useDotenv: true

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auction

custom:
   developer: ${env:DEVELOPER, ''}
   CloudNamingIdentifier:
    "${env:PROJECT_CODE}-${self:custom.developer}${env:APP_NAME}"
   MainTableName: dynamodb-${env:PROJECT_CODE}-main
