name: CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
      - run: npm ci
        working-directory: 'Backend'
      - run: npm run build --if-present
        working-directory: 'Backend'
      - run: npm test
        working-directory: 'Backend'
