name: CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'Backend/package-lock.json'
    - run: npm ci
      working-directory: 'Backend'
    - run: npm run eslint
      working-directory: 'Backend'
    - run: npm run jest
      working-directory: 'Backend'
